### ISSUE TITLE
Adding subfolder structure to snippets

### ISSUE THREAD

**Issue by efekurnaz** [tomaszbujnowicz/shopify-slater-tailwindcss#5]
Hey Tomasz!

Thank you so much for combining slater with tailwind, using this on a new project right now and it's amazing.

I'm trying to add a folder structure to snippets folder but couldn't output the files into snippets/ root. Do you have any idea how can I?

Example:
**from /snippets/components/foo.liquid
to /snippets/foo.liquid**

I have installed https://webpack.js.org/plugins/copy-webpack-plugin/

Added this to my slate.config.js, nothing happens. Still builds the folders as it is.

```
const CopyPlugin = require('copy-webpack-plugin');
...
plugins: [
    new CopyPlugin({
      patterns: [
        { 
          from: 'src/snippets/**/*',
          to: 'build/snippets/' }
      ],
    }),
  ]
...

**Comment by tomaszbujnowicz** [comment]
I wish I could help I am not sure how to make that work and is it doable at all.
So yeah, It's not me who wrote boilerplate.
The original project is placed here https://github.com/the-couch/slater made by guys at The Couch.
I just cloned it and played around with the Tailwind settings.
I believe they have added Tailwind support in the meantime so maybe it would make more sense to try to clone the original setup and ask the question in their GitHub. Hope you find a way to have it up and running ;)

**Comment by efekurnaz** [comment]
@tomaszbujnowicz thank you for your quick return :)

Got it, I thought it must be something simple but seems to be more complicated than I thought. 

I'll see if they can help, thanks again.
